Pr check for test-app
Signed-off-by: Lasse Ylivainio <lasse.ylivainio@alifsemi.com>

diff --git a/automation/Jenkinsfile_Pr b/automation/Jenkinsfile_Pr
--- a/automation/Jenkinsfile_Pr
+++ b/automation/Jenkinsfile_Pr
@@ -2,6 +2,9 @@ def Build_SW_Echo_Client = 'Pending'
 def Build_SW_Echo_Server = 'Pending'
 def Flash_board_echo_server = 'Pending'
 def Flash_board_echo_client = 'Pending'
+def smoke_tests = 'Pending'
+def Flash_board = 'Pendind'
+def Build_SW = 'Pending'
 
 pipeline {
     agent any
@@ -101,7 +104,6 @@ pipeline {
 
         stage('Flash the board for echo_client') {
             agent { label 'lasse' }
-            options { skipDefaultCheckout() }
             steps {
                 script {
                     catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
@@ -121,6 +123,7 @@ pipeline {
                             ./app-write-mram -p
                             popd
                             """
+                            reset_board()
                             Flash_board_echo_client = 'Pass'
                         } catch (Exception e) {
                             Flash_board_echo_client = 'Fail'
@@ -131,8 +134,7 @@ pipeline {
             }
         }
         stage('Flash the board for echo_server') {
-            agent { label 'lasse' }
-            options { skipDefaultCheckout() }
+            agent { label 'lasse' } 
             steps {
                 script {
                     catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
@@ -152,6 +154,7 @@ pipeline {
                             ./app-write-mram -p
                             popd
                             """
+                            reset_board()
                             Flash_board_echo_server = 'Pass'
                         } catch (Exception e) {
                             Flash_board_echo_server = 'Fail'
@@ -167,6 +170,159 @@ pipeline {
                 echo "Pipeline Pr check completed successfully for ${env.BRANCH_NAME}"
             }
         }
+		stage('Pr_Build for test-app') {
+            when {
+                anyOf {
+                    branch 'PR-*'
+                    branch 'main'
+                }
+            }
+			agent { label 'zephyr_alif_sdk_ble' }
+            options { skipDefaultCheckout() }
+            steps {
+                script {
+                    catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
+                        try{
+                            sh '''#!/bin/bash -xe
+                            pwd
+                            cd /root/alif
+                            west forall -c "git clean -fdx"
+							cd /root/alif/sdk-alif/
+                            git status
+                            if [[ -v CHANGE_ID ]]; then
+                                git branch -D pr-\${CHANGE_ID} || true
+                                git fetch origin pull/\${CHANGE_ID}/head:pr-\${CHANGE_ID}
+                                git checkout pr-\${CHANGE_ID}
+                            else
+                                git fetch origin -pu
+                                git checkout main
+                                git reset --hard origin/main
+                            fi
+                            cd ..
+                            west update
+                            ls -la
+                            cd /root/alif/sdk-alif/
+                            west build -p always -b alif_b1_dk_rtss_he applications/testapp
+                            cp /root/alif/sdk-alif/build/zephyr/zephyr.bin /root/workspace/spark_initial/
+                            mv /root/alif/sdk-alif/build /root/workspace/spark_initial/
+                            cd /root/workspace/spark_initial/
+                            tar -cvf build.tar build/
+                            ls -la
+                            pwd
+                            '''
+                            stash name: 'zephyr.bin', includes: 'zephyr.bin'
+                            Build_SW = 'Pass'
+                            } catch (Exception e) {
+                                Build_SW = 'Fail'
+                                error('Build failed')
+                        }
+                    }
+                }    
+			}
+			post {
+                always {
+                    archiveArtifacts artifacts: 'build.tar', fingerprint: true
+                }
+            }
+        } //end of stage Build
+		 stage('Flash and run Smoke test') {
+                agent { label 'lasse' }
+                steps {
+                    script {
+                        catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
+                            try{
+                                unstash name: 'zephyr.bin'
+                                sh """#!/bin/bash -xe
+                                pwd
+                                rsync -a --delete $ALIF_SETOOLS_ORIG $ALIF_SETOOLS_LOCATION
+                                cp zephyr.bin $ALIF_SETOOLS_LOCATION/build/images/test-app.bin
+                                cp ble_automation/B1-test-app.json $ALIF_SETOOLS_LOCATION/build/config/
+                                pushd $ALIF_SETOOLS_LOCATION
+                                sed -e 's/ttyUSB0/ttyAlifSEDUT1/g' isp_config_data_temp.cfg > isp_config_data.cfg
+                                ./tools-config -p "B1 (AB1C1F4M51820PH) - 1.8 MRAM / 2.0 SRAM" -r "A0"
+                                ./app-gen-toc --filename build/config/B1-test-app.json
+                                ./app-write-mram -p
+                                sed -e 's/ttyUSB0/ttyAlifSEDUT2/g' isp_config_data_temp.cfg > isp_config_data.cfg
+                                ./tools-config -p "B1 (AB1C1F4M51820PH) - 1.8 MRAM / 2.0 SRAM" -r "A0"
+                                ./app-gen-toc --filename build/config/B1-test-app.json
+                                ./app-write-mram -p
+                                pwd
+                                popd
+                                """
+                                reset_board()
+                                Flash_board = 'Pass'
+                            } catch (Exception e) {
+                                Flash_board = 'Fail'
+                                error('Flash_board failed')
+                            }
+                        }
+                        if ( Flash_board == 'Pass')
+                            {
+                                catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
+                                try{
+                                    unstash name: 'zephyr.bin'
+
+                                    sh """#!/bin/bash -xe
+                                    pwd
+                                    cd pytest
+                                    python3 -m venv venv
+                                    . venv/bin/activate
+                                    pip install -r requirements.txt
+                                    sed -e 's/ttyACM0/ttyAlifHEDUT1/g' -e 's/ttyACM1/ttyAlifHEDUT2/g' pytest_ini.template > pytest.ini
+                                    pytest tests --tb=no -s --root-logdir=pytest-logs
+                                    """
+
+                                    smoke_tests = 'Pass'
+                                } catch (Exception e) {
+                                smoke_tests = 'Fail'
+                                error('Smoke_tests failed')
+                                }
+                            }
+
+                        }
+
+                    }
+                }
+                post {
+                    always {
+                        archiveArtifacts artifacts: 'pytest/pytest-logs/**', fingerprint: true
+                    }
+                }
+        }
+		 stage('Done for test-app pr_check') {
+            steps {
+                echo "Pipeline Pr check for test_app completed successfully for ${env.BRANCH_NAME}"
+            }
+        }
+    }
+}
+def reset_board() {
+    def maxRetries = 10
+    def success = false
+
+    for (int attempt = 1; attempt <= maxRetries; attempt++) {
+        println " Attempt #${attempt} to reset board"
+
+        sh """#!/bin/bash -x
+            ykushcmd ykushxs -s $YKUSHDUT1 -d
+            ykushcmd ykushxs -s $YKUSHDUT2 -d
+            sleep 10
+            ykushcmd ykushxs -s $YKUSHDUT1 -u
+            ykushcmd ykushxs -s $YKUSHDUT2 -u
+            sleep 3
+            pwd 
+            ls -la
+        """
+        def checkStatus = sh(script: 'python3 automation/check_uart_output.py', returnStatus: true)
+        if (checkStatus == 0) {
+            success = true
+            break
+        } else {
+            println ' Retrying...'
+        }
+    }
+    if (!success) {
+        error " board did not respond after ${maxRetries} attempts!"
     }
 }
 
